[package]
name = "art_generator"
version = "0.1.0"
authors = ["Wybe <wybe@ruurdwestra.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
anyhow = "*"
rand = "*"